//GET http://localhost:3000/v1/ws



//GET http://localhost:3000/v1/websocket/connect

# GET http://localhost:4000/v1/websocket
# Connection: upgrade
# Upgrade: WebSocket


#GET http://localhost:4000/v1/websocket

GET http://localhost:4001/

# create new service to route to mockbin
# curl -i -X POST \
# --url http://localhost:4001/services/ \
# --data 'name=my-example-name' \
# --data 'url=mockbin.org'
